const ASSETS = {
    image: {
        "btn-default-title": "buttons/Button.png",
        "logo-game": `logos/logo_${navigator.language === 'pt-BR' ? 'pt' : 'en'}.png`,
        "logo-phaser": "logos/phaser_logo.png",
        "atlas-image": "map/atlas.png",
        "particle": "particles/particle_warp.png",
        "particle-smoke": "particles/particle_smoke.png",
        "close-button": "icons/close.png",
        "title-bg": "sprites/title-screen-bg.png",
        "full-hearth": "status/fullHearth.png",
        "empty-hearth": "status/emptyHearth.png",
        "bar": "scrollBar/bar-Photoroom.png",
        "track": "scrollBar/track-Photoroom.png",
        "minimap-background": "windows/bgMinimap.png",
        "bg-minimap": "windows/bgMinimap.png",
        "bg-popup": "windows/bgPopup.png",
        "bg-Dialog": "windows/bgDialog.png",
        "bg-battleScene": "backgrounds/battleSceneBackground.png"
    },

    spritesheet: {
        "Menu-btns-image": { path: "buttons/menu_buttons.png", frameWidth: 34, frameHeight: 34 },
        "social-media-spritesheet": { path: "icons/iconsSocialMedia.png", frameWidth: 32, frameHeight: 32 },

        "player-idle": { path: "player/idle.png", frameWidth: 42, frameHeight: 60 },
        "player-walk": { path: "player/walk.png", frameWidth: 32, frameHeight: 60 },
        "player-death": { path: "player/death.png", frameWidth: 48, frameHeight: 40 },
        "player-attack-guitar": { path: "player/playingGuitar.png", frameWidth: 34, frameHeight: 60 },
        "player-attack-flute": { path: "player/playingFlute.png", frameWidth: 38, frameHeight: 60 },

        "base-orc-idle": { path: "enemies/orcs/orc/idle.png", frameWidth: 32, frameHeight: 32 },
        "base-orc-run": { path: "enemies/orcs/orc/run.png", frameWidth: 24, frameHeight: 32 },
        "base-orc-death": { path: "enemies/orcs/orc/death.png", frameWidth: 64, frameHeight: 32 },

        "stickBug-walk": { path: "enemies/stickBug/walk.png", frameWidth: 60, frameHeight: 41 },
        "stickBug-disguised": { path: "enemies/stickBug/disguised.png", frameWidth: 56, frameHeight: 62 },
        "stickBug-changeState": { path: "enemies/stickBug/changeStance.png", frameWidth: 60, frameHeight: 62 },
        "stickBug-idleStandStill": { path: "enemies/stickBug/idleStandStill.png", frameWidth: 60, frameHeight: 38 },

        "john-cutting": { path: "npcs/john/cutting.png", frameWidth: 76, frameHeight: 72 },
        "maria-sweep": { path: "npcs/maria/sweep.png", frameWidth: 76, frameHeight: 72 },
        "balderson-sweep": { path: "npcs/balderson/cleaning.png", frameWidth: 76, frameHeight: 72 },
        "jazz-playing": { path: "npcs/jazz/playing.png", frameWidth: 76, frameHeight: 72 },
        "andressa-picking": { path: "npcs/andressa/picking.png", frameWidth: 76, frameHeight: 72 },
        "laplace-carrying": { path: "npcs/laplace/carrying.png", frameWidth: 76, frameHeight: 72 },
        "vincent-moving": { path: "npcs/vincent/moving.png", frameWidth: 76, frameHeight: 72 },
        "pietro-defeated": { path: "npcs/pietro/defeated.png", frameWidth: 76, frameHeight: 72 },
        "ethan-walking": { path: "npcs/ethan/walking.png", frameWidth: 76, frameHeight: 72 },
        "richard-walking": { path: "npcs/richard/walking.png", frameWidth: 76, frameHeight: 72 },
        "dog-itching": { path: "npcs/dog/itching.png", frameWidth: 76, frameHeight: 72 },
        "bento-walking": { path: "npcs/bento/walking.png", frameWidth: 76, frameHeight: 72 },
        "teobauto-idle": { path: "npcs/teobauto/shaking.png", frameWidth: 76, frameHeight: 72 },
        "raizela-idle": { path: "npcs/raizela/holding.png", frameWidth: 76, frameHeight: 72 },
        "maximo-idle": { path: "npcs/maximo/walking.png", frameWidth: 76, frameHeight: 72 },
        "clara-idle": { path: "npcs/clara/launching.png", frameWidth: 76, frameHeight: 72 },
        "eva-idle": { path: "npcs/eva/eating.png", frameWidth: 76, frameHeight: 72 },
        "adam-idle": { path: "npcs/adam/eating.png", frameWidth: 76, frameHeight: 72 },
        "adimetica-idle": { path: "npcs/adimetica/remove.png", frameWidth: 76, frameHeight: 72 },
        "agnes-idle": { path: "npcs/agnes/moving.png", frameWidth: 76, frameHeight: 72 },
        "aisha-idle": { path: "npcs/aisha/fighting.png", frameWidth: 76, frameHeight: 72 },
        "alcides-idle": { path: "npcs/alcides/beating.png", frameWidth: 76, frameHeight: 72 },
        "alex-idle": { path: "npcs/alex/carrying.png", frameWidth: 76, frameHeight: 72 },
        "alfred-idle": { path: "npcs/alfred/walking.png", frameWidth: 76, frameHeight: 72 },
        "alfred_com_plato-walking": { path: "npcs/alfred/working.png", frameWidth: 76, frameHeight: 72 },
        "algebrina-idle": { path: "npcs/algebrina/singing.png", frameWidth: 76, frameHeight: 72 },
        "alvoro-idle": { path: "npcs/alvoro/catching.png", frameWidth: 76, frameHeight: 72 },
        "amir-idle": { path: "npcs/amir/adjusting.png", frameWidth: 76, frameHeight: 72 },
        "augusto-idle": { path: "npcs/augusto/throwing.png", frameWidth: 76, frameHeight: 72 },
        "barbara-idle": { path: "npcs/barbara/moving.png", frameWidth: 76, frameHeight: 72 },
        "baribaldo-idle": { path: "npcs/baribaldo/action.png", frameWidth: 76, frameHeight: 72 },
        "benjamin-idle": { path: "npcs/benjamin/walking.png", frameWidth: 76, frameHeight: 72 },
        "camila-idle": { path: "npcs/camila/walking.png", frameWidth: 76, frameHeight: 72 },
        "catherine-idle": { path: "npcs/catherine/moving.png", frameWidth: 76, frameHeight: 72 },
        "chloe-idle": { path: "npcs/chloe/carrying.png", frameWidth: 76, frameHeight: 72 },
        "clarina_urso-idle": { path: "npcs/clarina/action.png", frameWidth: 76, frameHeight: 72 },
        "clarina_andando-idle": { path: "npcs/clarina/walking.png", frameWidth: 76, frameHeight: 72 },
        "cornelia-idle": { path: "npcs/cornelia/moving.png", frameWidth: 76, frameHeight: 72 },
        "daisy-idle": { path: "npcs/daisy/eating.png", frameWidth: 76, frameHeight: 72 },
        "dante-idle": { path: "npcs/dante/sweeping.png", frameWidth: 76, frameHeight: 72 },
        "darius-idle": { path: "npcs/darius/execute.png", frameWidth: 76, frameHeight: 72 },
        "darius_Ataque-idle": { path: "npcs/darius/execute3.png", frameWidth: 76, frameHeight: 72 },
        "dorothy-idle": { path: "npcs/dorothy/moving.png", frameWidth: 76, frameHeight: 72 },
        "edson-idle": { path: "npcs/edson/playing.png", frameWidth: 76, frameHeight: 72 },
        "feilong-idle": { path: "npcs/feilong/sweeping.png", frameWidth: 76, frameHeight: 72 },
        "flavio-idle": { path: "npcs/flavio/holding.png", frameWidth: 76, frameHeight: 72 },
        "fractalino-idle": { path: "npcs/fractalino/dancing.png", frameWidth: 76, frameHeight: 72 },
        "geo-idle": { path: "npcs/geo/crying.png", frameWidth: 76, frameHeight: 72 },
        "geometrina-idle": { path: "npcs/geometrina/pray.png", frameWidth: 76, frameHeight: 72 },
        "gideon-idle": { path: "npcs/gideon/uphead.png", frameWidth: 76, frameHeight: 72 },
        "hannah-idle": { path: "npcs/hannah/eating.png", frameWidth: 76, frameHeight: 72 },
        "hans-idle": { path: "npcs/hans/writing.png", frameWidth: 76, frameHeight: 72 },
        "helena-idle": { path: "npcs/helena/smelling.png", frameWidth: 76, frameHeight: 72 },
        "henova-idle": { path: "npcs/henova/thinking.png", frameWidth: 76, frameHeight: 72 },
        "inara-idle": { path: "npcs/inara/playing.png", frameWidth: 76, frameHeight: 72 },
        "irelene-idle": { path: "npcs/irelene/carrying.png", frameWidth: 76, frameHeight: 72 },
        "isaac-idle": { path: "npcs/isaac/smooth.png", frameWidth: 76, frameHeight: 72 },
        "jacob-idle": { path: "npcs/jacob/walking.png", frameWidth: 76, frameHeight: 72 },
        "jeronimo-idle": { path: "npcs/jeronimo/crying.png", frameWidth: 76, frameHeight: 72 },
        "joaquim-idle": { path: "npcs/joaquim/toasting.png", frameWidth: 76, frameHeight: 72 },
        "jose-idle": { path: "npcs/jose/working.png", frameWidth: 76, frameHeight: 72 },
        "kael-idle": { path: "npcs/kael/moving.png", frameWidth: 76, frameHeight: 72 },
        "laila-idle": { path: "npcs/laila/sweeping.png", frameWidth: 76, frameHeight: 72 },
        "lara-idle": { path: "npcs/lara/eating.png", frameWidth: 76, frameHeight: 72 },
        "laura-idle": { path: "npcs/laura/walking.png", frameWidth: 76, frameHeight: 72 },
        "legolas-idle": { path: "npcs/legolas/polishing.png", frameWidth: 76, frameHeight: 72 },
        "liam-idle": { path: "npcs/liam/walking.png", frameWidth: 76, frameHeight: 72 },
        "lily-idle": { path: "npcs/lily/walking.png", frameWidth: 76, frameHeight: 72 },
        "lina-idle": { path: "npcs/lina/reading.png", frameWidth: 76, frameHeight: 72 },
        "lorena-idle": { path: "npcs/lorena/crying.png", frameWidth: 76, frameHeight: 72 },
        "luke-idle": { path: "npcs/luke/carrying.png", frameWidth: 76, frameHeight: 72 },
        "lyra-idle": { path: "npcs/lyra/care.png", frameWidth: 76, frameHeight: 72 },
        "madalena-idle": { path: "npcs/madalena/dancing.png", frameWidth: 76, frameHeight: 72 },
        "magnus-idle": { path: "npcs/magnus/moving.png", frameWidth: 76, frameHeight: 72 },
        "manuel-idle": { path: "npcs/manuel/walking.png", frameWidth: 76, frameHeight: 72 },
        "manuel_comida-idle": { path: "npcs/manuel/working.png", frameWidth: 76, frameHeight: 72 },
        "marina-idle": { path: "npcs/marina/action.png", frameWidth: 76, frameHeight: 72 },
        "matheus-idle": { path: "npcs/matheus/playing.png", frameWidth: 76, frameHeight: 72 },
        "mathson-idle": { path: "npcs/mathson/writing.png", frameWidth: 76, frameHeight: 72 },
        "michael-idle": { path: "npcs/michael/eating.png", frameWidth: 76, frameHeight: 72 },
        "medionel-idle": { path: "npcs/medionel/swinging.png", frameWidth: 76, frameHeight: 72 },
        "miguel-idle": { path: "npcs/miguel/playing.png", frameWidth: 76, frameHeight: 72 },
        "newton-idle": { path: "npcs/newton/eating.png", frameWidth: 76, frameHeight: 72 },
        "noah-idle": { path: "npcs/noah/walking.png", frameWidth: 76, frameHeight: 72 },
        "nora-idle": { path: "npcs/nora/preaching.png", frameWidth: 76, frameHeight: 72 },
        "oliver-idle": { path: "npcs/oliver/carrying.png", frameWidth: 76, frameHeight: 72 },
        "oracio-idle": { path: "npcs/oracio/moving.png", frameWidth: 76, frameHeight: 72 },
        "oscar-idle": { path: "npcs/oscar/eating.png", frameWidth: 76, frameHeight: 72 },
        "parabolico-idle": { path: "npcs/parabolico/playing.png", frameWidth: 76, frameHeight: 72 },
        "poincare-idle": { path: "npcs/poincare/carry.png", frameWidth: 76, frameHeight: 72 },
        "radian-idle": { path: "npcs/radian/carry.png", frameWidth: 76, frameHeight: 72 },
        "rafael-idle": { path: "npcs/rafael/dead.png", frameWidth: 76, frameHeight: 72 },
        "ragnar-idle": { path: "npcs/ragnar/execute.png", frameWidth: 76, frameHeight: 72 },
        "raymond-idle": { path: "npcs/raymond/moving.png", frameWidth: 76, frameHeight: 72 },
        "richard-idle": { path: "npcs/richard/walking.png", frameWidth: 76, frameHeight: 72 },
        "rosalind-idle": { path: "npcs/rosalind/caring.png", frameWidth: 76, frameHeight: 72 },
        "salomao-idle": { path: "npcs/salomao/plowing.png", frameWidth: 76, frameHeight: 72 },
        "selma-idle": { path: "npcs/selma/shaking.png", frameWidth: 76, frameHeight: 72 },
        "simboletta-idle": { path: "npcs/simboletta/dancing.png", frameWidth: 76, frameHeight: 72 },
        "sophie-idle": { path: "npcs/sophie/crying.png", frameWidth: 76, frameHeight: 72 },
        "tadeu-idle": { path: "npcs/tadeu/working.png", frameWidth: 76, frameHeight: 72 },
        "teodoro-idle": { path: "npcs/teodoro/carrying3.png", frameWidth: 76, frameHeight: 72 },
        "thorne-idle": { path: "npcs/thorne/moving.png", frameWidth: 76, frameHeight: 72 },
        "tina-idle": { path: "npcs/tina/smelling.png", frameWidth: 76, frameHeight: 72 },
        "tomas-idle": { path: "npcs/tomas/holding.png", frameWidth: 76, frameHeight: 72 },
        "viktor-idle": { path: "npcs/viktor/training.png", frameWidth: 76, frameHeight: 72 },
        "vithor-idle": { path: "npcs/vithor/moving.png", frameWidth: 76, frameHeight: 72 },
        "whitecat-idle": { path: "npcs/whitecat/sleeping.png", frameWidth: 76, frameHeight: 72 },
        "william-idle": { path: "npcs/william/eating.png", frameWidth: 76, frameHeight: 72 }
    },

    video: {
        "background-animated-1": "backgrounds/background.mp4"
    },
    audio: {
        "music-background-menu": "sounds/Path_to_Lake_Land.ogg",
        "music-background-game": "sounds/sketch4.mp3",
        "music-background-castle": "sounds/Loop_The_Old_Tower_Inn.wav",
        "music-background-vila": "sounds/The_Old_Tower_Inn.mp3",
        "music-background-combate": "sounds/battleThemeA.mp3",
  
    },
    json: {
        "npcData": "npcs/createNpc.json"
    },
    tilemapJSON: {
        "map-JSON": "map/map1.json"
    }
}

export default ASSETS

